### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by VenkatCM** [lemieuxm/tdameritrade#3]
Hi,

I encountered this error when running your program. Would you please advise me where we should the code to where it works?

json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Venkat

**Comment by lemieuxm** [comment]
It looks like it is having trouble reading a JSON string or file.  Could you post the whole stack trace?  On what line did it occur?

-Matthew

On October 14, 2018 at 14:32:43, VenkatCM (notifications@github.com) wrote:

Hi,

I encountered this error when running your program. Would you please advise me where we should the code to where it works?

json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Venkat

**Comment by VenkatCM** [comment]
examples adm$ python3 news_story.py 
Traceback (most recent call last):
  File "news_story.py", line 30, in <module>
    main()
  File "news_story.py", line 24, in main
    tdstream = tds.TDStream()
  File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdstream.py", line 47, in __init__
    self.userInfo = self.tdh.getStreamerInfo()
  File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdhelper.py", line 224, in getStreamerInfo
    data = self.getUserPrincipals("streamerSubscriptionKeys,streamerConnectionInfo")
  File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdhelper.py", line 229, in getUserPrincipals
    data = self.doget(url, reqvars = {'fields': fields})
  File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdhelper.py", line 165, in doget
    authManager = AuthManager()
  File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdhelper.py", line 42, in __init__
    self.config = json.load(file)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by lemieuxm** [comment]
Did you create ~/.mltrading/config/td_app_config?

It seems that this file is somehow not properly formatted json.   See the Notes in the README.md file.  

-Matthew

On October 16, 2018 at 06:11:14, VenkatCM (notifications@github.com) wrote:

examples adm$ python3 news_story.py
Traceback (most recent call last):
File "news_story.py", line 30, in
main()
File "news_story.py", line 24, in main
tdstream = tds.TDStream()
File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdstream.py", line 47, in init
self.userInfo = self.tdh.getStreamerInfo()
File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdhelper.py", line 224, in getStreamerInfo
data = self.getUserPrincipals("streamerSubscriptionKeys,streamerConnectionInfo")
File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdhelper.py", line 229, in getUserPrincipals
data = self.doget(url, reqvars = {'fields': fields})
File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdhelper.py", line 165, in doget
authManager = AuthManager()
File "/usr/local/lib/python3.7/site-packages/tdameritrade-0.1.2-py3.7.egg/tdameritrade/td/tdhelper.py", line 42, in init
self.config = json.load(file)
File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/init.py", line 296, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/init.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by lemieuxm** [comment]
Closing.  Seems to have been resolved.
